"""
Django settings for kofeinya_backend project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

DJANGO_ENV = os.environ.get("DJANGO_ENV", "development").lower().strip()
IS_PRODUCTION = DJANGO_ENV in ("prod", "production")

# В продакшене DJANGO_SECRET_KEY обязателен (без небезопасного дефолта).
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "")
if not SECRET_KEY:
    if IS_PRODUCTION:
        raise RuntimeError("DJANGO_SECRET_KEY must be set in production")
    SECRET_KEY = "django-insecure-dev-only"

DEBUG = os.environ.get("DJANGO_DEBUG", ("false" if IS_PRODUCTION else "true")).lower() in ("1", "true", "yes")

def _split_csv(value: str) -> list[str]:
    return [x.strip() for x in (value or "").split(",") if x.strip()]


_allowed_hosts_default = "localhost,127.0.0.1,0.0.0.0" if not IS_PRODUCTION else ""
ALLOWED_HOSTS = _split_csv(os.environ.get("DJANGO_ALLOWED_HOSTS", _allowed_hosts_default))
if IS_PRODUCTION and not ALLOWED_HOSTS:
    raise RuntimeError("DJANGO_ALLOWED_HOSTS must be set in production")

# CORS: в dev можно разрешить всё, в prod — только whitelist из env.
if DEBUG and not IS_PRODUCTION:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = _split_csv(os.environ.get("CORS_ALLOWED_ORIGINS", ""))
    if IS_PRODUCTION and not CORS_ALLOWED_ORIGINS:
        raise RuntimeError("CORS_ALLOWED_ORIGINS must be set in production")
# Токены передаются в заголовке Authorization, cookies для API не нужны.
CORS_ALLOW_CREDENTIALS = False

_csrf_default = "http://localhost:5173,http://127.0.0.1:5173" if not IS_PRODUCTION else ""
CSRF_TRUSTED_ORIGINS = _split_csv(os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", _csrf_default))
if IS_PRODUCTION and not CSRF_TRUSTED_ORIGINS:
    raise RuntimeError("DJANGO_CSRF_TRUSTED_ORIGINS must be set in production")

# Ссылка в письме подтверждения (фронтенд).
FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://127.0.0.1:5173").rstrip("/")

# DaData: токен для автоподстановки адреса.
DADATA_TOKEN = os.environ.get("DADATA_TOKEN", "")

# Почта: в разработке письма выводятся в консоль (см. runserver).
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "noreply@example.local")
SERVER_EMAIL = DEFAULT_FROM_EMAIL

if EMAIL_BACKEND == "django.core.mail.backends.smtp.EmailBackend":
    EMAIL_HOST = os.environ.get("EMAIL_HOST", "localhost")
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "true").lower() in ("1", "true", "yes")
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")

if IS_PRODUCTION:
    SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "false").lower() in ("1", "true", "yes")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "same-origin"
    SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"
    SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get("SECURE_HSTS_INCLUDE_SUBDOMAINS", "true").lower() in ("1", "true", "yes")
    SECURE_HSTS_PRELOAD = os.environ.get("SECURE_HSTS_PRELOAD", "true").lower() in ("1", "true", "yes")
    X_FRAME_OPTIONS = "DENY"

    # Если приложение за reverse proxy и тот терминирует TLS — включаем доверие к X-Forwarded-Proto.
    BEHIND_PROXY = os.environ.get("DJANGO_BEHIND_PROXY", "false").lower() in ("1", "true", "yes")
    if BEHIND_PROXY:
        USE_X_FORWARDED_HOST = True
        SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'csp',
    'accounts.apps.AccountsConfig',
    'menu',
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    # Безопасный дефолт: закрываем всё, что не помечено явно как AllowAny.
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    # Базовая защита от брутфорса/спама на API (глобально).
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": os.environ.get("DRF_THROTTLE_ANON", "120/minute"),
        "user": os.environ.get("DRF_THROTTLE_USER", "600/minute"),
    },
}

# Ограничения на загрузки, чтобы не убить память большими файлами.
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get("DJANGO_DATA_UPLOAD_MAX_MEMORY_SIZE", str(10 * 1024 * 1024)))  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get("DJANGO_FILE_UPLOAD_MAX_MEMORY_SIZE", str(10 * 1024 * 1024)))  # 10MB

# CORP заголовок по умолчанию выключен, чтобы не ломать dev и сценарий,
# когда фронтенд и API на разных доменах/портах. Включайте только при
# необходимости и когда домены/политика понятны.
ENABLE_CORP_HEADER = os.environ.get("ENABLE_CORP_HEADER", "false").lower() in ("1", "true", "yes")
CROSS_ORIGIN_RESOURCE_POLICY = os.environ.get("CROSS_ORIGIN_RESOURCE_POLICY", "same-origin")

# CSP (Content Security Policy): базовый строгий профиль для SPA.
# Для dev часто мешает HMR — включаем только в prod.
if IS_PRODUCTION:
    CONTENT_SECURITY_POLICY = {
        "DIRECTIVES": {
            "default-src": ("'self'",),
            "base-uri": ("'self'",),
            "frame-ancestors": ("'none'",),
            "form-action": ("'self'",),
            "object-src": ("'none'",),
            "img-src": ("'self'", "data:", "blob:"),
            "style-src": ("'self'", "'unsafe-inline'"),
            "script-src": ("'self'",),
            "connect-src": ("'self'",),
            "upgrade-insecure-requests": True,
            "block-all-mixed-content": True,
        }
    }

# Логирование: в prod пишем INFO, security предупреждения не скрываем.
LOG_LEVEL = os.environ.get("DJANGO_LOG_LEVEL", "INFO" if IS_PRODUCTION else "DEBUG")
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {"format": "%(levelname)s %(asctime)s %(name)s %(message)s"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "standard"},
    },
    "root": {"handlers": ["console"], "level": LOG_LEVEL},
    "loggers": {
        "django.security": {"handlers": ["console"], "level": "WARNING", "propagate": False},
        "rest_framework": {"handlers": ["console"], "level": "INFO", "propagate": False},
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
    'kofeinya_backend.security_headers.SecurityHeadersMiddleware',
]

ROOT_URLCONF = 'kofeinya_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kofeinya_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'
