# Generated by Django 6.0.3 on 2026-03-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_order_type_and_cash_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Фото'),
        ),
    ]
