# Generated by Django 5.2.10 on 2026-05-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='promotions/banners/', verbose_name='Изображение шапки'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='conditions',
            field=models.TextField(blank=True, default='', verbose_name='Условия акции'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания акции'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='promotions/pdf/', verbose_name='PDF файл'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='pdf_link_text',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Текст ссылки на PDF'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='terms',
            field=models.TextField(blank=True, default='', verbose_name='Пользовательское соглашение'),
        ),
    ]
