# Generated by Django 5.2.10 on 2026-05-16 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_promotion_banner_image_promotion_conditions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена (для скидки)')),
                ('active_from', models.DateTimeField(blank=True, null=True, verbose_name='Активно с')),
                ('active_until', models.DateTimeField(blank=True, null=True, verbose_name='Активно до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_of_day', to='menu.product', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Блюдо дня',
                'verbose_name_plural': 'Блюда дня',
                'ordering': ['-created_at'],
            },
        ),
    ]
