# Generated by Django 5.2.10 on 2026-05-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_dishoftheday'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishoftheday',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой'),
        ),
    ]
