# Generated by Django 6.0.3 on 2026-05-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='code_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Код действует до'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_phone_verified',
            field=models.BooleanField(default=False, verbose_name='Телефон подтверждён'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_code',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Код подтверждения'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_method',
            field=models.CharField(blank=True, choices=[('telegram', 'Telegram'), ('max', 'MAX')], default='', max_length=10, verbose_name='Способ подтверждения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32, unique=True, verbose_name='Телефон'),
        ),
    ]
