# Generated by Django 5.2.10 on 2026-05-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_telegram_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('title_style', models.CharField(blank=True, choices=[('', 'Обычный'), ('bold', 'Жирный'), ('italic', 'Курсив'), ('underline', 'Подчеркнутый'), ('strikethrough', 'Зачеркнутый'), ('code', 'Код'), ('spoiler', 'Спойлер')], default='bold', max_length=20, verbose_name='Стиль заголовка')),
                ('text', models.TextField(blank=True, verbose_name='Текст сообщения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='broadcasts/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Количество отправленных')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['-created_at'],
            },
        ),
    ]
